"""Real-filing replay test for the FV-v2 scorer rewire (PR #31).

The pre-fix predictions ARTL, TVRD, KIDZ all landed at confidence=0.0000
because the rules-v1 scorer's keys had zero overlap with FEATURE_KEYS_FV_V1.
PR #31 rewired the scorer to FV-v2 vocabulary; the integration test in
that PR uses a synthetic "all flags True" fixture and only proves the
wiring works, not that real EDGAR filings produce non-zero scores.

This test is the stronger version: it loads JSON snapshots of the actual
sec_filings rows that produced ARTL/TVRD/KIDZ, runs them through the
new FV-v2 extractor + scorer, and asserts:

  1. Each filing produces a non-zero confidence under the new scorer
  2. The expected weight-firing pattern matches the filing's content
     (e.g., S-3 effective filings have edgar_priority_form=True;
     filings on EDGAR_PRIORITY_FORMS with no IR firm have only the
     priority-form weight firing, etc.)

We deliberately do NOT pin exact confidence values — the assertion is
on which weights fire, not on the sum. Future weight tuning will move
the numbers; the firing pattern is the stable contract.

Fixtures are generated by `scripts/snapshot_replay_fixtures.py` against
the production DB. If the fixture directory is empty, this test SKIPS
rather than fails, so CI doesn't block on missing snapshot data; the PR
that ships the fixtures un-skips by inclusion.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from config import constants
from signals.features.edgar_features import (
    FEATURE_KEYS_FV_V2,
    extract_edgar_features,
)
from signals.scoring.catalyst_scorer import RulesV1Scorer, _RULES_V1_WEIGHTS


FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "replay"


def _load_fixtures() -> list[tuple[str, dict]]:
    """Return [(label, snapshot_dict)] for every JSON fixture present.

    Empty list when the dir doesn't exist or has no .json files — the
    parametrized test will skip with a clear message rather than fail.
    """
    if not FIXTURE_DIR.exists():
        return []
    out: list[tuple[str, dict]] = []
    for path in sorted(FIXTURE_DIR.glob("*.json")):
        with open(path) as f:
            data = json.load(f)
        out.append((path.stem, data))
    return out


_FIXTURES = _load_fixtures()


@pytest.mark.skipif(
    not _FIXTURES,
    reason="No replay fixtures present. Run scripts/snapshot_replay_fixtures.py "
           "on the droplet to generate tests/fixtures/replay/*.json.",
)
@pytest.mark.parametrize(
    "label,snapshot",
    _FIXTURES,
    ids=[label for label, _ in _FIXTURES] if _FIXTURES else None,
)
def test_real_filing_replay_scores_nonzero_under_fv_v2(label, snapshot):
    """For each real filing that produced a fv-v1 confidence=0 prediction,
    the FV-v2 extractor + scorer must produce a non-zero score.

    Per-filing expectations are derived from the fixture content (no
    hardcoded ticker-specific knowledge in this test):

      - If the filing's form_type is in EDGAR_PRIORITY_FORMS,
        edgar_priority_form must fire (0.20)
      - If ir_firm_mentioned is non-empty, ir_firm_engaged must fire
      - If the caller-resolved ir_firm_known_promoter is True, that fires
      - If the caller-resolved underwriter_flagged is True, that fires
      - If full_text["reverse_split"] is non-null, reverse_split fires
      - If form4_transaction_code == 'P', is_form4_buy fires (FV-v2 narrow)

    A filing on a priority form will fire AT MINIMUM edgar_priority_form
    (0.20), which by itself produces probability 0.20 — well above 0.

    We do NOT assert exact confidence values. Weight tuning moves the
    sum; the firing pattern is the stable contract.
    """
    filing = snapshot["filing"]
    ticker_metadata = snapshot["ticker_metadata"]

    # Run extractor + scorer
    features = extract_edgar_features(filing, ticker_metadata)
    result = RulesV1Scorer().score(features)

    # FV-v2 schema-version pin
    assert result.feature_schema_version == constants.FEATURE_SCHEMA_VERSION
    assert result.feature_schema_version == "fv-v2"

    # Build the per-filing expectation set FROM THE FIXTURE (not hardcoded).
    expected_firing: dict[str, bool] = {}

    form_type = (filing.get("form_type") or "").strip()
    if form_type in constants.EDGAR_PRIORITY_FORMS:
        expected_firing["edgar_priority_form"] = True

    if filing.get("ir_firm_mentioned"):
        expected_firing["ir_firm_engaged"] = True

    if ticker_metadata.get("ir_firm_known_promoter"):
        expected_firing["ir_firm_known_promoter"] = True

    if ticker_metadata.get("underwriter_flagged"):
        expected_firing["underwriter_flagged"] = True

    full_text = filing.get("full_text") or {}
    if isinstance(full_text, dict) and full_text.get("reverse_split"):
        expected_firing["reverse_split"] = True

    code = (filing.get("form4_transaction_code") or "").strip().upper()
    if code == "P":
        expected_firing["is_form4_buy"] = True

    # Verify each expected firing actually fires under FV-v2.
    for key, want in expected_firing.items():
        assert features[key] == want, (
            f"[{label}] expected {key}={want} based on fixture content; "
            f"extractor returned {features[key]!r}"
        )

    # If ANY weight is expected to fire, the score must be > 0. The
    # contrapositive — no expected firing means we'd accept 0 — is also
    # honest: a filing with none of the FV-v2 signals shouldn't score.
    # In practice every priority-form filing fires at least one weight.
    if expected_firing:
        assert result.probability > 0.0, (
            f"[{label}] expected non-zero score given fixture content "
            f"({sorted(expected_firing.keys())}); got {result.probability}. "
            "This is the regression: FV-v2 extractor + scorer must produce "
            "non-zero confidence on real filings that hit any weight key."
        )

    # Sanity: pre-fix confidence_v1 was 0.0000 — confirm the snapshot
    # captured that state, so we know the fixture is the right baseline.
    if snapshot.get("prediction_confidence_v1") is not None:
        assert snapshot["prediction_confidence_v1"] == pytest.approx(0.0, abs=1e-6), (
            f"[{label}] expected prediction_confidence_v1==0.0 (the bug "
            f"this PR validates the fix for); fixture has "
            f"{snapshot['prediction_confidence_v1']}"
        )


@pytest.mark.skipif(
    not _FIXTURES,
    reason="No replay fixtures present.",
)
def test_replay_fixtures_cover_all_three_pre_fix_predictions():
    """Sanity check: the fixture set should cover ARTL, TVRD, and KIDZ.
    If a snapshot is missing, the bug-fix verification is incomplete."""
    tickers_present = {snap["prediction_ticker"] for _, snap in _FIXTURES}
    expected = {"ARTL", "TVRD", "KIDZ"}
    missing = expected - tickers_present
    assert not missing, (
        f"missing fixtures for: {missing}. Run "
        "scripts/snapshot_replay_fixtures.py on the droplet to regenerate."
    )


@pytest.mark.skipif(
    not _FIXTURES,
    reason="No replay fixtures present.",
)
def test_every_replay_fixture_has_all_fv_v2_input_fields():
    """Each fixture must contain every field the FV-v2 extractor reads;
    otherwise the test would silently treat missing fields as None and
    under-fire weights."""
    expected_filing_keys = {
        "form_type", "ir_firm_mentioned", "s3_effective",
        "form4_insider_buy", "form4_transaction_code",
        "underwriter_id", "full_text", "item_numbers",
    }
    expected_meta_keys = {
        "exchange", "float_shares", "promoter_match_count",
        "ir_firm_known_promoter", "underwriter_flagged",
    }
    for label, snap in _FIXTURES:
        missing_filing = expected_filing_keys - set(snap["filing"].keys())
        missing_meta = expected_meta_keys - set(snap["ticker_metadata"].keys())
        assert not missing_filing, (
            f"[{label}] fixture missing filing fields: {missing_filing}"
        )
        assert not missing_meta, (
            f"[{label}] fixture missing ticker_metadata fields: {missing_meta}"
        )
